Extend example
nonbanana/grpc_study pull request #2
Opened 2024-05-09 08:44 UTC by yunochi

NodeJS의 스트리밍 예제를 보강하고, 선택적 값과 oneof를 사용하는 내용, message안에 message등을 프로토콜에 추가했습니다.

2024-05-10 00:21 UTC, nonbanana requested changes
기여에 감사드립니다! 제가 부족하게 서술한 부분에 더 조사를 진행하여서 채워주신 부분이라던가, 추가된 예제에서 protobuf와 grpc의 중요 기능들에 대해서 서술 해 주신 것 같아 굉장히 좋았습니다. node에 익숙하셔서 개발 환경 관련패키지를 추가 해 주신것은 말 할 것도 없이 좋은 기여이고요.

**다만 추가해주신 새로운 streaming 예제는 별도의 step으로 분리하여 넣는것이 어떨까요?**  추가해주신 코드가 streaming의 본질에 맞고 include등의 예시를 보여주는 등 **기술적 예제로서 매우 훌륭하다고 생각합니다**. 그러나 커넥션 외에도 이런 저런 이야기가 들어있어 사람들이 헷깔릴 수도 있을 것 같다고 생각됩니다. 제가 기존에 넣었던 예제는 unary와 streaming 커넥션을 설명 하는 데에만 집중해서 예제를 만들었었는데요, 노드와 gRPC를 처음 보는 사람들의 이해를 돕기 위함이였습니다. 사람들이 처음 grpc에 접근 할 때는 unary와 streaming 커넥션의 개념을 먼저 확인해보기 위해 list data streaming정도만 먼저 실행 해 본 다음, 추가해주신 부분들을 보게 끔 하는 편이 조금 더 이해하기 쉬울 것 같아 보입니다.

제가 생각하는 방안은 
* server를 두개로 나누어서 server_connection_example.ts server_{something}_example.ts  파일을 만들기
* 전자는 풀 리퀘 이전의 내용을 그대로 살려두고, 후자에 현재 추가해주신 예제를 넣기
* readme에는 이전 streaming 서술 내용 다음에 추가
하는 정도를 생각해봤는데 어떨까요? 혹시 다른 식으로 하는게 더 좋을 것 같다면 의견을 부탁 드리겠습니다.

2024-05-10 00:21 UTC, nonbanana commented on grpc_node/.prettierrc
> +    "tabWidth": 2
헛... 4로 하면... 안되나요......ㅠㅠ

2024-05-13 09:43 UTC, yunochi commented on grpc_node/.prettierrc
> +    "tabWidth": 2
2가 JS/TS 생태계에서 표준에 가깝게 사용하는 들여쓰기다 보니, 2로 정했습니다.

2024-05-13 09:47 UTC, yunochi commented
서버 / 클라이언트를 unary예제와 stream예제로 분리하고, 문서를 보강/업데이트 했습니다.  기존에 만들어 주셨던 GetListData구현도 살리려고 했었는데, unary와 stream으로 예제를 분리하다 보니 어디에 넣어야 할지 애매해져서 일단 놔뒀습니다.

2024-05-14 00:29 UTC, nonbanana commented
앗... 제가 의도를 전달할때 충분히 전달드리지 못한 모양이네요ㅠㅠ 기존 구현이였던 GetListData를 streaming 예제로 넣고, 확장된 streaming예제로서 추가해주신 부분을 넣자는 의미였습니다

2024-05-14 01:38 UTC, nonbanana approved these changes

2024-05-14 01:40 UTC, merged